/**
 * INSTRUCTIFY KENYA — EDUCATIONAL RESOURCE DATA HUB
 * Comprehensive repository of curriculum-aligned tools, templates,
 * media assets, frameworks, and pedagogical guides.
 */

window.RESOURCES_DATA = (function() {
  'use strict';

  // ── 1. Statistics Counters ─────────────────────────────────
  const statistics = [
    { id: 'total-resources', count: 184, suffix: '+', label: 'Available Resources', icon: 'books' },
    { id: 'templates', count: 68, suffix: '+', label: 'Downloadable Templates', icon: 'file-text' },
    { id: 'pd-materials', count: 52, suffix: '+', label: 'Professional Learning Modules', icon: 'award' },
    { id: 'categories', count: 12, suffix: '', label: 'Specialized Categories', icon: 'grid' },
    { id: 'contributors', count: 40, suffix: '+', label: 'Expert Contributors', icon: 'users' }
  ];

  // ── 2. 12 Quick Resource Categories ────────────────────────
  const categories = [
    {
      id: 'teaching-learning',
      name: 'Teaching and Learning Materials',
      icon: 'book-open',
      color: 'blue',
      description: 'Instructional aids, interactive classroom activities, and subject-specific teaching toolkits.',
      count: 28
    },
    {
      id: 'cbc-cbe',
      name: 'CBC and CBE Resources',
      icon: 'compass',
      color: 'teal',
      description: 'Competency-based curriculum designs, core competency frameworks, and strand guides.',
      count: 32
    },
    {
      id: 'lesson-plans',
      name: 'Lesson Plans and Schemes of Work',
      icon: 'calendar',
      color: 'purple',
      description: 'Termly schemes, daily lesson plan templates, and CBC learning outcome matrices.',
      count: 24
    },
    {
      id: 'assessment-tools',
      name: 'Assessment and Evaluation Tools',
      icon: 'check-square',
      color: 'amber',
      description: 'Formative rubrics, portfolio assessment guides, self-evaluation checklists, and scoring keys.',
      count: 20
    },
    {
      id: 'edtech-guides',
      name: 'Educational Technology Guides',
      icon: 'monitor',
      color: 'blue',
      description: 'Smart classroom setup guides, digital tool integration manuals, and software tutorials.',
      count: 18
    },
    {
      id: 'teacher-pd',
      name: 'Teacher Professional Development',
      icon: 'award',
      color: 'teal',
      description: 'TPAD alignment materials, digital literacy training manuals, and reflective practice logs.',
      count: 16
    },
    {
      id: 'school-leadership',
      name: 'School Leadership and Management',
      icon: 'briefcase',
      color: 'purple',
      description: 'Strategic planning toolkits, institutional ICT policies, and supervisory frameworks.',
      count: 14
    },
    {
      id: 'ict-infrastructure',
      name: 'ICT Infrastructure Resources',
      icon: 'server',
      color: 'blue',
      description: 'Computer lab deployment blueprints, network safety checklists, and hardware maintenance guides.',
      count: 12
    },
    {
      id: 'inclusive-education',
      name: 'Inclusive and Special Needs Education',
      icon: 'heart',
      color: 'rose',
      description: 'Differentiated instruction strategies, assistive technology guides, and IEP templates.',
      count: 10
    },
    {
      id: 'parental-engagement',
      name: 'Parental Engagement Resources',
      icon: 'home',
      color: 'amber',
      description: 'Home-learning support manuals, CBC parent orientation packs, and communication tools.',
      count: 8
    },
    {
      id: 'career-guidance',
      name: 'Learner Career Guidance',
      icon: 'target',
      color: 'teal',
      description: 'Senior school pathway roadmaps, STEM career exploration kits, and mentorship logs.',
      count: 9
    },
    {
      id: 'digital-safety',
      name: 'Digital Safety and Citizenship',
      icon: 'shield',
      color: 'purple',
      description: 'Child online protection guidelines, cyberbullying prevention toolkits, and school internet policies.',
      count: 11
    }
  ];

  // ── 3. Featured Resources (8 High-Value Materials) ─────────
  const featured = [
    {
      id: 'feat-1',
      title: 'CBC Lesson Planning & Strand Alignment Toolkit',
      category: 'CBC and CBE Resources',
      categoryId: 'cbc-cbe',
      format: 'Toolkit',
      audience: 'Teachers & Trainers',
      educationLevel: 'Junior School',
      access: 'Free',
      readTime: '30 mins',
      updatedAt: 'Aug 2026',
      rating: 4.9,
      downloads: 1420,
      image: 'assets/images/course_assessment_mastery.jpg',
      description: 'A complete step-by-step master toolkit for crafting learner-centered, competency-focused lesson plans with integrated formative rubrics and CBC strands.',
      fileType: 'ZIP (DOCX + PDF)',
      fileSize: '3.4 MB',
      downloadUrl: '#download-feat-1'
    },
    {
      id: 'feat-2',
      title: 'Teacher Digital Skills & Smart Classroom Starter Guide',
      category: 'Educational Technology Guides',
      categoryId: 'edtech-guides',
      format: 'PDF',
      audience: 'Teachers',
      educationLevel: 'Professional Development',
      access: 'Free',
      readTime: '25 mins',
      updatedAt: 'Aug 2026',
      rating: 4.8,
      downloads: 980,
      image: 'assets/images/course_smart_vr_classroom.jpg',
      description: 'Essential hands-on guide covering classroom presentation software, interactive digital whiteboards, safe educational search, and cloud resource storage.',
      fileType: 'PDF Guide',
      fileSize: '2.8 MB',
      downloadUrl: '#download-feat-2'
    },
    {
      id: 'feat-3',
      title: 'School ICT Infrastructure Readiness & Audit Checklist',
      category: 'ICT Infrastructure Resources',
      categoryId: 'ict-infrastructure',
      format: 'Excel',
      audience: 'School Leaders & ICT Coordinators',
      educationLevel: 'Education Institutions',
      access: 'Free',
      readTime: '15 mins',
      updatedAt: 'Sep 2026',
      rating: 4.9,
      downloads: 740,
      image: 'assets/images/consultancy_ict_network.jpg',
      description: 'Institutional audit template to inspect LAN wiring, power backup readiness, device health, cyber hygiene, and classroom multimedia accessibility.',
      fileType: 'XLSX Spreadsheet',
      fileSize: '1.2 MB',
      downloadUrl: '#download-feat-3'
    },
    {
      id: 'feat-4',
      title: 'Competency-Based Assessment Rubric Bank (Grades 1–9)',
      category: 'Assessment and Evaluation Tools',
      categoryId: 'assessment-tools',
      format: 'Word',
      audience: 'Teachers & School Leaders',
      educationLevel: 'Primary & Junior School',
      access: 'Free',
      readTime: '40 mins',
      updatedAt: 'Aug 2026',
      rating: 5.0,
      downloads: 2150,
      image: 'assets/images/home_interactive_teaching.jpg',
      description: 'Over 60 ready-to-use holistic assessment rubrics aligned with core competencies: critical thinking, communication, collaboration, and self-efficacy.',
      fileType: 'DOCX Document',
      fileSize: '4.6 MB',
      downloadUrl: '#download-feat-4'
    },
    {
      id: 'feat-5',
      title: 'Parent’s Guide to Supporting Digital Learning at Home',
      category: 'Parental Engagement Resources',
      categoryId: 'parental-engagement',
      format: 'PDF',
      audience: 'Parents & Guardians',
      educationLevel: 'Primary School',
      access: 'Free',
      readTime: '18 mins',
      updatedAt: 'Jul 2026',
      rating: 4.7,
      downloads: 890,
      image: 'assets/images/home_teacher_coaching.jpg',
      description: 'Practical handbook for parents to create productive home learning routines, manage screen time constructively, and collaborate with school teachers.',
      fileType: 'PDF Handbook',
      fileSize: '1.9 MB',
      downloadUrl: '#download-feat-5'
    },
    {
      id: 'feat-6',
      title: 'Digital Safety & Child Online Protection Handbook for Schools',
      category: 'Digital Safety and Citizenship',
      categoryId: 'digital-safety',
      format: 'PDF',
      audience: 'Education Institutions & Teachers',
      educationLevel: 'Junior & Senior School',
      access: 'Free',
      readTime: '22 mins',
      updatedAt: 'Aug 2026',
      rating: 4.9,
      downloads: 1120,
      image: 'assets/images/course_ict_integration.jpg',
      description: 'Institutional guidelines for safe internet usage, data privacy compliance under Kenyan law, reporting protocols, and cyber resilience training.',
      fileType: 'PDF Policy Manual',
      fileSize: '2.5 MB',
      downloadUrl: '#download-feat-6'
    },
    {
      id: 'feat-7',
      title: 'Inclusive Classroom & Differentiated Instruction Master Kit',
      category: 'Inclusive and Special Needs Education',
      categoryId: 'inclusive-education',
      format: 'Toolkit',
      audience: 'Special Needs & General Teachers',
      educationLevel: 'Early Years & Primary School',
      access: 'Premium',
      readTime: '35 mins',
      updatedAt: 'Aug 2026',
      rating: 4.95,
      downloads: 650,
      image: 'assets/images/consultancy_smart_boards.jpg',
      description: 'Evidence-based strategies, multisensory activity templates, and individualized learning support plans for neurodiverse classrooms.',
      fileType: 'ZIP (Toolkit + Videos)',
      fileSize: '8.2 MB',
      downloadUrl: '#download-feat-7'
    },
    {
      id: 'feat-8',
      title: 'Institutional Educational Technology Integration Framework',
      category: 'School Leadership and Management',
      categoryId: 'school-leadership',
      format: 'PowerPoint',
      audience: 'School Leaders & Consultants',
      educationLevel: 'Teacher Education',
      access: 'Free',
      readTime: '20 mins',
      updatedAt: 'Sep 2026',
      rating: 4.85,
      downloads: 820,
      image: 'assets/images/home_digital_leadership.jpg',
      description: 'Comprehensive presentation deck and roadmap template for institutional boards to plan sustainable 3-year EdTech transitions.',
      fileType: 'PPTX Presentation',
      fileSize: '5.1 MB',
      downloadUrl: '#download-feat-8'
    }
  ];

  // ── 4. Comprehensive Resource Library (24 Items) ───────────
  const library = [
    {
      id: 'res-1',
      title: 'Junior School Integrated Science Practical Activity Guide',
      category: 'Teaching and Learning Materials',
      categoryId: 'teaching-learning',
      audience: 'Teachers',
      educationLevel: 'Junior School',
      format: 'PDF',
      access: 'Free',
      date: '2026-08-20',
      rating: 4.9,
      downloads: 890,
      language: 'English',
      image: 'assets/images/home_hero_classroom.jpg',
      description: 'Laboratory safety, low-cost experimental setups, and student observation sheets designed for Grade 7, 8, and 9 Integrated Science strands.',
      fileSize: '3.1 MB',
      tags: ['CBC', 'Science', 'Practicals', 'Lab Safety']
    },
    {
      id: 'res-2',
      title: 'CBC Core Competencies Matrix & Evidence Logging Sheet',
      category: 'CBC and CBE Resources',
      categoryId: 'cbc-cbe',
      audience: 'Teachers',
      educationLevel: 'Primary School',
      format: 'Excel',
      access: 'Free',
      date: '2026-08-15',
      rating: 4.8,
      downloads: 1280,
      language: 'English',
      image: 'assets/images/course_assessment_mastery.jpg',
      description: 'Streamlined spreadsheets to track and report learner growth in Communication, Collaboration, Critical Thinking, and Digital Literacy.',
      fileSize: '1.4 MB',
      tags: ['CBC', 'Competencies', 'Evidence', 'Continuous Assessment']
    },
    {
      id: 'res-3',
      title: 'Termly Scheme of Work Template for Junior Secondary',
      category: 'Lesson Plans and Schemes of Work',
      categoryId: 'lesson-plans',
      audience: 'Teachers',
      educationLevel: 'Junior School',
      format: 'Word',
      access: 'Free',
      date: '2026-08-28',
      rating: 4.95,
      downloads: 3410,
      language: 'English',
      image: 'assets/images/about_strategy_session.jpg',
      description: 'Officially formatted, editable Term 1, 2, and 3 scheme templates with pre-configured columns for sub-strands, specific learning outcomes, and assessment modes.',
      fileSize: '650 KB',
      tags: ['Schemes of Work', 'Lesson Plans', 'Junior School', 'Templates']
    },
    {
      id: 'res-4',
      title: 'Classroom Observation & Teacher Coaching Form',
      category: 'School Leadership and Management',
      categoryId: 'school-leadership',
      audience: 'School leaders',
      educationLevel: 'Teacher Education',
      format: 'PDF',
      access: 'Free',
      date: '2026-08-10',
      rating: 4.75,
      downloads: 610,
      language: 'English',
      image: 'assets/images/home_teacher_coaching.jpg',
      description: 'Peer observation rubric and supportive pedagogical feedback guide designed for instructional coaches, heads of departments, and principals.',
      fileSize: '1.1 MB',
      tags: ['Observation', 'Leadership', 'TPAD', 'Teacher Mentorship']
    },
    {
      id: 'res-5',
      title: 'AI in Teaching: Ethical Prompting Framework for Educators',
      category: 'Educational Technology Guides',
      categoryId: 'edtech-guides',
      audience: 'Teachers',
      educationLevel: 'Professional Development',
      format: 'Article',
      access: 'Free',
      date: '2026-09-01',
      rating: 5.0,
      downloads: 1890,
      language: 'English',
      image: 'assets/images/course-ai.png',
      description: 'How to use generative AI responsibly for lesson planning, differentiated reading comprehension passages, and formative quiz design.',
      fileSize: 'Online & PDF',
      tags: ['AI', 'Teacher Training', 'Digital Learning', 'Ethics']
    },
    {
      id: 'res-6',
      title: 'Student Portfolio Assessment Rubric & Self-Reflection Journal',
      category: 'Assessment and Evaluation Tools',
      categoryId: 'assessment-tools',
      audience: 'Learners',
      educationLevel: 'Junior School',
      format: 'Template',
      access: 'Free',
      date: '2026-07-29',
      rating: 4.85,
      downloads: 940,
      language: 'English',
      image: 'assets/images/home_interactive_teaching.jpg',
      description: 'Printable and digital self-assessment portfolio journal where learners record reflections, artifacts, and target goals throughout the term.',
      fileSize: '2.2 MB',
      tags: ['Assessment', 'Portfolios', 'Self-Reflection', 'CBC']
    },
    {
      id: 'res-7',
      title: 'Computer Lab Maintenance Schedule & Device Logbook',
      category: 'ICT Infrastructure Resources',
      categoryId: 'ict-infrastructure',
      audience: 'ICT coordinators',
      educationLevel: 'Education institutions',
      format: 'Excel',
      access: 'Free',
      date: '2026-08-12',
      rating: 4.7,
      downloads: 520,
      language: 'English',
      image: 'assets/images/consultancy_ict_network.jpg',
      description: 'Weekly device health checklist, preventive hardware maintenance logbook, thermal monitoring record, and software license tracker.',
      fileSize: '890 KB',
      tags: ['ICT Infrastructure', 'Computer Lab', 'Maintenance', 'Checklists']
    },
    {
      id: 'res-8',
      title: 'Differentiated Lesson Planning Template for Inclusive Classes',
      category: 'Inclusive and Special Needs Education',
      categoryId: 'inclusive-education',
      audience: 'Teachers',
      educationLevel: 'Early Years Education',
      format: 'Word',
      access: 'Free',
      date: '2026-08-05',
      rating: 4.9,
      downloads: 730,
      language: 'English',
      image: 'assets/images/about_educator_workshop.jpg',
      description: 'Three-tiered instruction plan accommodating diverse learning paces, visual/auditory preferences, and tailored formative tasks.',
      fileSize: '780 KB',
      tags: ['Special Needs', 'Inclusion', 'Differentiation', 'Lesson Plans']
    },
    {
      id: 'res-9',
      title: 'Senior School Career Pathways & Subject Selection Handbook',
      category: 'Learner Career Guidance',
      categoryId: 'career-guidance',
      audience: 'Learners',
      educationLevel: 'Senior School',
      format: 'PDF',
      access: 'Free',
      date: '2026-08-25',
      rating: 4.95,
      downloads: 1650,
      language: 'English',
      image: 'assets/images/home_stem_collaboration.jpg',
      description: 'A comprehensive roadmap demystifying the three CBC Senior School pathways: Arts & Sports, Social Sciences, and STEM.',
      fileSize: '3.8 MB',
      tags: ['Career Guidance', 'Senior School', 'Pathways', 'STEM']
    },
    {
      id: 'res-10',
      title: 'Interactive Phonics & Early Literacy Sound Cards (EYE)',
      category: 'Teaching and Learning Materials',
      categoryId: 'teaching-learning',
      audience: 'Teachers',
      educationLevel: 'Early Years Education',
      format: 'Toolkit',
      access: 'Free',
      date: '2026-07-15',
      rating: 4.8,
      downloads: 1120,
      language: 'English',
      image: 'assets/images/home_interactive_teaching.jpg',
      description: 'Printable color flashcards and audio pronunciation links for foundational phonemic awareness in Pre-Primary 1 and 2.',
      fileSize: '5.2 MB',
      tags: ['Early Years', 'Literacy', 'Phonics', 'Flashcards']
    },
    {
      id: 'res-11',
      title: 'Whole-School Digital Readiness Self-Assessment Toolkit',
      category: 'School Leadership and Management',
      categoryId: 'school-leadership',
      audience: 'School leaders',
      educationLevel: 'Professional Development',
      format: 'Toolkit',
      access: 'Premium',
      date: '2026-08-30',
      rating: 4.9,
      downloads: 410,
      language: 'English',
      image: 'assets/images/home_digital_leadership.jpg',
      description: 'Institutional readiness diagnostic evaluating leadership commitment, teacher digital maturity, infrastructure resilience, and parental support.',
      fileSize: '4.1 MB',
      tags: ['Digital Readiness', 'Leadership', 'Audit', 'Strategic Planning']
    },
    {
      id: 'res-12',
      title: 'Classroom Screen Time & Cyberbullying Prevention Lesson Plan',
      category: 'Digital Safety and Citizenship',
      categoryId: 'digital-safety',
      audience: 'Teachers',
      educationLevel: 'Junior School',
      format: 'Word',
      access: 'Free',
      date: '2026-08-18',
      rating: 4.85,
      downloads: 870,
      language: 'English',
      image: 'assets/images/course_ict_integration.jpg',
      description: '45-minute interactive lesson plan with roleplays, case studies, and discussion prompts on healthy digital habits and reporting online harassment.',
      fileSize: '950 KB',
      tags: ['Digital Safety', 'Cyberbullying', 'Citizenship', 'Lesson Plans']
    },
    {
      id: 'res-13',
      title: 'TPAD 2 Evidence Portfolio Compilation Guide for Teachers',
      category: 'Teacher Professional Development',
      categoryId: 'teacher-pd',
      audience: 'Teachers',
      educationLevel: 'Professional Development',
      format: 'PDF',
      access: 'Free',
      date: '2026-08-02',
      rating: 4.9,
      downloads: 2430,
      language: 'English',
      image: 'assets/images/course_assessment_mastery.jpg',
      description: 'Step-by-step documentation manual detailing exact evidence requirements for professional knowledge, time management, and learner progression.',
      fileSize: '2.7 MB',
      tags: ['TPAD', 'TSC', 'Teacher Training', 'Portfolios']
    },
    {
      id: 'res-14',
      title: 'Parent-Teacher Communication Log & Meeting Agenda Kit',
      category: 'Parental Engagement Resources',
      categoryId: 'parental-engagement',
      audience: 'Parents and guardians',
      educationLevel: 'Primary School',
      format: 'Word',
      access: 'Free',
      date: '2026-07-22',
      rating: 4.75,
      downloads: 680,
      language: 'English',
      image: 'assets/images/home_teacher_coaching.jpg',
      description: 'Constructive meeting agendas, parent inquiry follow-up templates, and collaborative student improvement contracts.',
      fileSize: '720 KB',
      tags: ['Parental Engagement', 'Communication', 'Meetings', 'Templates']
    },
    {
      id: 'res-15',
      title: 'School ICT Policy & Acceptable Use Blueprint',
      category: 'ICT Infrastructure Resources',
      categoryId: 'ict-infrastructure',
      audience: 'Education institutions',
      educationLevel: 'Education Institutions',
      format: 'Word',
      access: 'Free',
      date: '2026-08-14',
      rating: 4.8,
      downloads: 790,
      language: 'English',
      image: 'assets/images/consultancy_ict_network.jpg',
      description: 'Comprehensive policy template covering institutional Wi-Fi, staff BYOD (Bring Your Own Device), student tablet rules, and data backups.',
      fileSize: '1.3 MB',
      tags: ['ICT Policy', 'BYOD', 'Acceptable Use', 'Institutions']
    },
    {
      id: 'res-16',
      title: 'Micro-Learning Module: Designing Formative Micro-Quizzes',
      category: 'Educational Technology Guides',
      categoryId: 'edtech-guides',
      audience: 'Teacher trainers',
      educationLevel: 'Teacher Education',
      format: 'Course',
      access: 'Free',
      date: '2026-08-27',
      rating: 4.9,
      downloads: 910,
      language: 'English',
      image: 'assets/images/course-digital.png',
      description: 'Interactive mini-course with templates on using Google Forms, Kahoot, and Plickers for low-friction, high-insight classroom feedback.',
      fileSize: 'Interactive Online',
      tags: ['Quizzes', 'EdTech', 'Formative Assessment', 'Google Forms']
    },
    {
      id: 'res-17',
      title: 'STEM Robotics & Coding Starter Activities for Primary Learners',
      category: 'Teaching and Learning Materials',
      categoryId: 'teaching-learning',
      audience: 'Teachers',
      educationLevel: 'Primary School',
      format: 'Toolkit',
      access: 'Premium',
      date: '2026-08-22',
      rating: 5.0,
      downloads: 1150,
      language: 'English',
      image: 'assets/images/home_stem_collaboration.jpg',
      description: 'Block-coding challenges with Scratch and offline computational thinking games designed for Kenyan upper primary classes.',
      fileSize: '6.5 MB',
      tags: ['STEM', 'Coding', 'Robotics', 'Computational Thinking']
    },
    {
      id: 'res-18',
      title: 'Junior School Social Studies Mapwork & Fieldwork Journal',
      category: 'Teaching and Learning Materials',
      categoryId: 'teaching-learning',
      audience: 'Teachers',
      educationLevel: 'Junior School',
      format: 'PDF',
      access: 'Free',
      date: '2026-08-08',
      rating: 4.8,
      downloads: 640,
      language: 'English',
      image: 'assets/images/course-cbe.png',
      description: 'Cartography exercises, local topographical analysis, and community environmental field research guidelines for Grade 8.',
      fileSize: '3.3 MB',
      tags: ['Social Studies', 'Mapwork', 'Fieldwork', 'Junior School']
    },
    {
      id: 'res-19',
      title: 'Special Education Needs (SEN) Individualized Education Plan (IEP)',
      category: 'Inclusive and Special Needs Education',
      categoryId: 'inclusive-education',
      audience: 'Education consultants',
      educationLevel: 'Teacher Education',
      format: 'Word',
      access: 'Free',
      date: '2026-08-16',
      rating: 4.95,
      downloads: 850,
      language: 'English',
      image: 'assets/images/about_strategy_session.jpg',
      description: 'Customizable IEP template detailing learner accommodations, sensory goals, behavioral milestones, and multi-disciplinary therapist input.',
      fileSize: '1.2 MB',
      tags: ['SEN', 'IEP', 'Inclusion', 'Special Needs']
    },
    {
      id: 'res-20',
      title: 'Audio Masterclass: Leading Sustainable Digital Transitions in Schools',
      category: 'School Leadership and Management',
      categoryId: 'school-leadership',
      audience: 'School leaders',
      educationLevel: 'Professional Development',
      format: 'Audio',
      access: 'Free',
      date: '2026-08-31',
      rating: 4.85,
      downloads: 720,
      language: 'English',
      image: 'assets/images/home_digital_leadership.jpg',
      description: '32-minute audio briefing for principals on balancing device budgets, overcoming teacher tech resistance, and measuring learning gains.',
      fileSize: '29 MB (Audio)',
      tags: ['Podcast', 'Leadership', 'Change Management', 'EdTech']
    },
    {
      id: 'res-21',
      title: 'Senior Secondary Career Portfolio and Apprenticeship Tracker',
      category: 'Learner Career Guidance',
      categoryId: 'career-guidance',
      audience: 'Learners',
      educationLevel: 'Senior School',
      format: 'Excel',
      access: 'Free',
      date: '2026-08-19',
      rating: 4.75,
      downloads: 580,
      language: 'English',
      image: 'assets/images/home_stem_collaboration.jpg',
      description: 'Personal tracker for job shadowing hours, industry mentorship logs, portfolio projects, and TVET / university admission requirements.',
      fileSize: '950 KB',
      tags: ['Career Guidance', 'Senior School', 'Apprenticeships', 'Portfolios']
    },
    {
      id: 'res-22',
      title: 'School Cybersecurity Drill & Incident Response Protocol',
      category: 'Digital Safety and Citizenship',
      categoryId: 'digital-safety',
      audience: 'ICT coordinators',
      educationLevel: 'Education institutions',
      format: 'PDF',
      access: 'Free',
      date: '2026-08-24',
      rating: 4.9,
      downloads: 690,
      language: 'English',
      image: 'assets/images/consultancy_ict_network.jpg',
      description: 'Procedures for managing student account compromises, ransomware prevention, sensitive student data leaks, and emergency communications.',
      fileSize: '1.8 MB',
      tags: ['Cybersecurity', 'Incident Response', 'Data Protection', 'ICT']
    },
    {
      id: 'res-23',
      title: 'Interactive Mathematics Manipulatives Guide for Grade 4–6',
      category: 'Teaching and Learning Materials',
      categoryId: 'teaching-learning',
      audience: 'Teachers',
      educationLevel: 'Primary School',
      format: 'PDF',
      access: 'Free',
      date: '2026-07-28',
      rating: 4.85,
      downloads: 1340,
      language: 'English',
      image: 'assets/images/course_smart_vr_classroom.jpg',
      description: 'Step-by-step visual models for teaching fractions, decimals, area, and volume using tangible local materials and free virtual simulators.',
      fileSize: '3.6 MB',
      tags: ['Mathematics', 'Primary', 'Manipulatives', 'CBC']
    },
    {
      id: 'res-24',
      title: 'Master Video Tutorial: Setting up ClassVR & 3D Interactive Models',
      category: 'Educational Technology Guides',
      categoryId: 'edtech-guides',
      audience: 'ICT coordinators',
      educationLevel: 'Education institutions',
      format: 'Video',
      access: 'Free',
      date: '2026-09-02',
      rating: 4.95,
      downloads: 1040,
      language: 'English',
      image: 'assets/images/course_smart_vr_classroom.jpg',
      description: 'Visual walkthrough of connecting VR headsets, synchronizing educational 3D biology and geography experiences, and teacher controls.',
      fileSize: '18 mins (Full HD)',
      tags: ['ClassVR', 'Virtual Reality', 'EdTech', 'Hardware']
    }
  ];

  // ── 5. Downloadable Templates & Practical Toolkits (16 Items)
  const toolkits = [
    {
      id: 'tool-1',
      title: 'Standard CBC Daily Lesson Plan Template',
      category: 'Lesson Plans',
      fileType: 'DOCX',
      fileSize: '380 KB',
      editable: true,
      audience: 'Primary & Junior Teachers',
      updatedAt: 'Aug 2026',
      downloads: 4820,
      description: 'Standardized 5-stage lesson plan including Introduction, Exploration, Explanation, Elaboration, and Assessment Rubric.'
    },
    {
      id: 'tool-2',
      title: 'Termly Scheme of Work Master Grid',
      category: 'Schemes of Work',
      fileType: 'XLSX',
      fileSize: '620 KB',
      editable: true,
      audience: 'All Teachers',
      updatedAt: 'Aug 2026',
      downloads: 3950,
      description: 'Pre-formatted spreadsheet featuring automated week calculation, lesson counts, strand mapping, and resource columns.'
    },
    {
      id: 'tool-3',
      title: 'Competency-Based Assessment Rubric Builder',
      category: 'Assessment Tools',
      fileType: 'DOCX',
      fileSize: '510 KB',
      editable: true,
      audience: 'Educators & Examiners',
      updatedAt: 'Jul 2026',
      downloads: 2190,
      description: '4-level grading rubric framework (Exceeding, Meeting, Approaching, Below Expectation) with customizable indicator banks.'
    },
    {
      id: 'tool-4',
      title: 'Learner Holistic Progress Record Sheet',
      category: 'Assessment Tools',
      fileType: 'XLSX',
      fileSize: '780 KB',
      editable: true,
      audience: 'Class Teachers',
      updatedAt: 'Aug 2026',
      downloads: 1840,
      description: 'Termly continuous assessment tracker capturing values, core competencies, subject scores, and teacher remarks.'
    },
    {
      id: 'tool-5',
      title: 'Peer Classroom Observation & Coaching Protocol',
      category: 'Leadership & TPAD',
      fileType: 'PDF',
      fileSize: '450 KB',
      editable: false,
      audience: 'HODs & Mentors',
      updatedAt: 'Jul 2026',
      downloads: 1120,
      description: 'Standardized diagnostic coaching tool with structured pre-lesson, during-lesson, and post-conference feedback sections.'
    },
    {
      id: 'tool-6',
      title: 'Teacher Professional Development (TPD) Plan',
      category: 'Professional Learning',
      fileType: 'DOCX',
      fileSize: '410 KB',
      editable: true,
      audience: 'Educators',
      updatedAt: 'Aug 2026',
      downloads: 1670,
      description: 'Personalized annual CPD goal-setting matrix aligned with TSC TPAD 2 requirements and peer-study circles.'
    },
    {
      id: 'tool-7',
      title: 'School ICT Infrastructure Audit Checklist',
      category: 'Infrastructure',
      fileType: 'XLSX',
      fileSize: '890 KB',
      editable: true,
      audience: 'ICT Coordinators',
      updatedAt: 'Sep 2026',
      downloads: 1450,
      description: 'Diagnostic audit covering network bandwidth, uninterruptible power supplies, antivirus status, and classroom displays.'
    },
    {
      id: 'tool-8',
      title: 'Institutional Digital Readiness Assessment Matrix',
      category: 'Leadership',
      fileType: 'PDF',
      fileSize: '950 KB',
      editable: false,
      audience: 'School Leaders',
      updatedAt: 'Aug 2026',
      downloads: 980,
      description: 'Framework scoring an institution across 6 pillars: Vision, Pedagogy, Infrastructure, Staff Capacity, Culture, and Community.'
    },
    {
      id: 'tool-9',
      title: 'Computer Lab Maintenance & Sanitization Checklist',
      category: 'Infrastructure',
      fileType: 'DOCX',
      fileSize: '340 KB',
      editable: true,
      audience: 'Lab Technicians',
      updatedAt: 'Jul 2026',
      downloads: 870,
      description: 'Daily, weekly, and monthly maintenance procedures to prolong hardware life and maintain hygienic student workstations.'
    },
    {
      id: 'tool-10',
      title: 'Parental Engagement Action Plan Template',
      category: 'Community',
      fileType: 'DOCX',
      fileSize: '420 KB',
      editable: true,
      audience: 'School Administrators',
      updatedAt: 'Aug 2026',
      downloads: 760,
      description: 'Calendarized strategy for hosting termly academic clinics, digital literacy workshops for parents, and CBC orientation days.'
    },
    {
      id: 'tool-11',
      title: 'School Improvement Planning (SIP) Matrix',
      category: 'Leadership',
      fileType: 'DOCX',
      fileSize: '680 KB',
      editable: true,
      audience: 'Principals & Boards',
      updatedAt: 'Aug 2026',
      downloads: 1320,
      description: 'Multi-year strategic roadmap matrix identifying baseline indicators, measurable targets, budgetary requirements, and KPIs.'
    },
    {
      id: 'tool-12',
      title: 'Educational Workshop Planning & Evaluation Form',
      category: 'Training',
      fileType: 'PDF',
      fileSize: '510 KB',
      editable: false,
      audience: 'Facilitators & Trainers',
      updatedAt: 'Jul 2026',
      downloads: 930,
      description: 'Logistics checklist and anonymous participant evaluation survey capturing content relevance, facilitator effectiveness, and takeaways.'
    },
    {
      id: 'tool-13',
      title: 'EdTech Project Proposal & Budget Template',
      category: 'Leadership',
      fileType: 'DOCX',
      fileSize: '540 KB',
      editable: true,
      audience: 'School Heads & Donors',
      updatedAt: 'Aug 2026',
      downloads: 1180,
      description: 'Standard grant-writing structure for securing hardware, solar installations, and connectivity funding from partners.'
    },
    {
      id: 'tool-14',
      title: 'Learner Career Pathway Exploration Logbook',
      category: 'Career Guidance',
      fileType: 'PDF',
      fileSize: '790 KB',
      editable: false,
      audience: 'Junior & Senior Learners',
      updatedAt: 'Aug 2026',
      downloads: 1540,
      description: 'Reflective self-discovery workbook connecting student aptitudes, interests, and academic performance with future careers.'
    },
    {
      id: 'tool-15',
      title: 'Staff Training Needs Assessment (TNA) Survey',
      category: 'Professional Learning',
      fileType: 'DOCX',
      fileSize: '360 KB',
      editable: true,
      audience: 'School Leaders',
      updatedAt: 'Jul 2026',
      downloads: 890,
      description: 'Comprehensive staff diagnostic instrument measuring confidence levels across digital tools, CBC strategies, and student wellness.'
    },
    {
      id: 'tool-16',
      title: 'SAMR Model Technology Integration Framework',
      category: 'EdTech',
      fileType: 'PDF',
      fileSize: '620 KB',
      editable: false,
      audience: 'Teachers & Trainers',
      updatedAt: 'Aug 2026',
      downloads: 2050,
      description: 'Visual pedagogical chart guiding educators from simple Substitution to profound Redefinition of learning tasks using tech.'
    }
  ];

  // ── 6. Learning Media Hub (8 Items) ────────────────────────
  const media = [
    {
      id: 'media-1',
      title: 'Mastering the CBC Competency-Based Assessment Framework',
      mediaType: 'Webinar Recording',
      duration: '48:15',
      presenter: 'Dr. Faith M. & Alex Larry',
      date: 'Aug 2026',
      topic: 'CBC & Assessment',
      thumbnail: 'assets/images/course_assessment_mastery.jpg',
      description: 'A deep-dive recorded workshop detailing practical methods to evaluate critical thinking, collaboration, and learner portfolios without grading overload.',
      views: '3.4k',
      videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ' // sample embeddable player
    },
    {
      id: 'media-2',
      title: 'Transforming Traditional Classrooms into Interactive Smart Hubs',
      mediaType: 'Video Tutorial',
      duration: '22:40',
      presenter: 'Eng. Kelvin N., EdTech Lead',
      date: 'Aug 2026',
      topic: 'EdTech Integration',
      thumbnail: 'assets/images/consultancy_smart_boards.jpg',
      description: 'Walkthrough of smart board calibration, wireless casting from teacher laptops, interactive whiteboards, and digital note distribution.',
      views: '2.8k',
      videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ'
    },
    {
      id: 'media-3',
      title: 'Instructify Podcast: The Future of AI in African Classrooms',
      mediaType: 'Podcast Episode',
      duration: '36:10',
      presenter: 'Alex Larry with Guest Educators',
      date: 'Sep 2026',
      topic: 'Artificial Intelligence',
      thumbnail: 'assets/images/course-ai.png',
      description: 'Episode 14 discussing how AI can empower rural and urban Kenyan teachers rather than replace them, with real classroom case studies.',
      views: '4.1k',
      audioUrl: 'podcast.html'
    },
    {
      id: 'media-4',
      title: 'Live Classroom Demonstration: Active Inquiry & Hands-On Science',
      mediaType: 'Classroom Demo',
      duration: '19:30',
      presenter: 'Grace O., Lead STEM Coach',
      date: 'Aug 2026',
      topic: 'Teaching Strategies',
      thumbnail: 'assets/images/home_hero_classroom.jpg',
      description: 'Unedited classroom footage demonstrating how to facilitate group investigation, question prompts, and learner-led presentations.',
      views: '1.9k',
      videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ'
    },
    {
      id: 'media-5',
      title: 'Teacher Interview: Transitioning to Junior Secondary with Confidence',
      mediaType: 'Teacher Interview',
      duration: '16:45',
      presenter: 'Peter K., Senior JSS Instructor',
      date: 'Jul 2026',
      topic: 'CBC Implementation',
      thumbnail: 'assets/images/home_teacher_coaching.jpg',
      description: 'Candid conversation on handling strand pacing, collaborating with peers, and building meaningful student rapport under CBC.',
      views: '2.1k',
      videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ'
    },
    {
      id: 'media-6',
      title: 'Cybersecurity for Schools: Protecting Learner Data and Wi-Fi',
      mediaType: 'Webinar Recording',
      duration: '42:00',
      presenter: 'Security Advisory Council',
      date: 'Aug 2026',
      topic: 'Digital Safety',
      thumbnail: 'assets/images/consultancy_ict_network.jpg',
      description: 'Essential webinar on safeguarding institutional passwords, student records, Wi-Fi router isolation, and phishing awareness.',
      views: '1.5k',
      videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ'
    },
    {
      id: 'media-7',
      title: 'ClassVR Virtual Field Trips: Bringing Geography to Life',
      mediaType: 'Technology Tutorial',
      duration: '14:20',
      presenter: 'Alex Larry, EdTech Specialist',
      date: 'Sep 2026',
      topic: 'EdTech Integration',
      thumbnail: 'assets/images/course_smart_vr_classroom.jpg',
      description: 'How to transport learners to the Great Rift Valley, Egyptian pyramids, and the International Space Station using immersive ClassVR headsets.',
      views: '3.1k',
      videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ'
    },
    {
      id: 'media-8',
      title: 'Micro-Learning: Formative Feedback that Inspires Learner Grit',
      mediaType: 'Professional Learning',
      duration: '12:05',
      presenter: 'Mercy W., Educational Psychologist',
      date: 'Aug 2026',
      topic: 'Teaching Strategies',
      thumbnail: 'assets/images/home_digital_leadership.jpg',
      description: 'Concrete examples of actionable verbal and written feedback that foster growth mindsets and reduce student test anxiety.',
      views: '2.5k',
      videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ'
    }
  ];

  // ── 7. Latest Articles & Education Insights (6 Items) ──────
  const articles = [
    {
      id: 'art-1',
      title: 'Decoding the CBC Senior School Pathways: A Practical Guide for Leaders',
      category: 'CBC & Curriculum',
      author: 'Alex Larry',
      date: 'Sep 2, 2026',
      readTime: '6 min read',
      image: 'assets/images/home_stem_collaboration.jpg',
      summary: 'How secondary school boards and principals can strategically prepare staffing, workshops, and science laboratories for the upcoming Senior School pathways.',
      tags: ['CBC', 'Senior School', 'Education Policy'],
      link: 'blog.html'
    },
    {
      id: 'art-2',
      title: 'Beyond the Smartboard: 5 Pedagogical Shifts that Actually Improve Learning',
      category: 'Digital Learning',
      author: 'Instructify Research Team',
      date: 'Aug 28, 2026',
      readTime: '5 min read',
      image: 'assets/images/course_smart_vr_classroom.jpg',
      summary: 'Hardware alone does not transform learning. Explore the teacher mindset shifts and active inquiry strategies that turn passive screens into active collaboration.',
      tags: ['EdTech', 'Pedagogy', 'Classrooms'],
      link: 'blog.html'
    },
    {
      id: 'art-3',
      title: 'Artificial Intelligence in the Kenyan Classroom: Friend or Foe?',
      category: 'Artificial Intelligence',
      author: 'Eng. Kelvin N.',
      date: 'Aug 24, 2026',
      readTime: '8 min read',
      image: 'assets/images/course-ai.png',
      summary: 'Addressing concerns over academic integrity while unlocking AI’s immense potential for individualized remedial lessons, language translation, and teacher efficiency.',
      tags: ['AI', 'Ethics', 'Innovation'],
      link: 'blog.html'
    },
    {
      id: 'art-4',
      title: 'Building a Reliable School Computer Lab on a Modest Budget',
      category: 'ICT Infrastructure',
      author: 'Alex Larry',
      date: 'Aug 17, 2026',
      readTime: '7 min read',
      image: 'assets/images/consultancy_ict_network.jpg',
      summary: 'Proven strategies for selecting durable hardware, optimizing power backups with solar inverters, and choosing low-maintenance open-source learning tools.',
      tags: ['Infrastructure', 'Hardware', 'Schools'],
      link: 'consultancy.html'
    },
    {
      id: 'art-5',
      title: 'Continuous Assessment vs. Final Exams: Cultivating Learner Competence',
      category: 'Assessment & Feedback',
      author: 'Dr. Faith M.',
      date: 'Aug 10, 2026',
      readTime: '5 min read',
      image: 'assets/images/course_assessment_mastery.jpg',
      summary: 'Why ongoing authentic assessment provides truer insights into student potential, creative problem-solving, and socio-emotional readiness than single-day exams.',
      tags: ['Assessment', 'CBC', 'Grit'],
      link: 'blog.html'
    },
    {
      id: 'art-6',
      title: 'Inclusive Education: Practical Assistive Technology in Resource-Constrained Schools',
      category: 'Inclusive Learning',
      author: 'Grace O.',
      date: 'Aug 3, 2026',
      readTime: '6 min read',
      image: 'assets/images/consultancy_smart_boards.jpg',
      summary: 'How simple smartphone voice-to-text, large print visual aids, and peer tutoring networks can welcome and empower neurodivergent learners.',
      tags: ['Inclusion', 'Special Needs', 'Accessibility'],
      link: 'blog.html'
    }
  ];

  return {
    statistics,
    categories,
    featured,
    library,
    toolkits,
    media,
    articles
  };
})();
